version: '3.6'
services:
  backend_idp:
    image: oanadi/idp:backend
    ports:
      - "8888:5000"
    hostname: server
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
    ports:
      - "55432:5432"

  admin:
    image: oanadi/idp:dbadmin
    hostname: admin
    depends_on:
      - backend
      - db

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - admin
      - backend