version: '3.6'
services:
  backend:
    image: oanadi/idp:backend
    ports:
      - "5000:5000"
    hostname: server
    volumes:
      - 'shared:/usr/src/app/shared/'
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
    ports:
      - "5432:5432"

  admin:
    image: oanadi/idp:dbadmin
    hostname: admin
    tty: true
    stdin_open: true
    volumes:
      - 'shared:/usr/src/app/shared/'
    depends_on:
      - backend

  client:
    image: oanadi/idp:client
    ports:
      - "8080:80"
    hostname: client
    depends_on:
      - backend

  metrics:
    image: prom/prometheus:latest
    container_name: metrics
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - backend

volumes:
  shared:
    driver: local 

  prometheus: {}