version: "3"
services:
  web:
    image: raduioanciobanu/idp:example
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
networks:
  webnet: